# ------------- VARIABLES
# Configure them in https://gitlab.satoshiengineering.com/satoshiengineering/lightning-tip-cards/-/settings/ci_cd
# ----- GLOBAL
# - DEPLOY_USER
# - DEPLOY_USER_SSH_KEY # can be found in sate access
# ----- BACKEND
# - BACKEND_DEPLOY_PATH_DEVELOP
# - BACKEND_DEPLOY_SERVER_DEVELOP
# - BACKEND_ENV_FILE_DEVELOP
# - BACKEND_PM2_APP_NAME_DEVELOP
# ----- FRONTEND
# - FRONTEND_DEPLOY_PATH_DEVELOP
# - FRONTEND_DEPLOY_SERVER_DEVELOP
# - FRONTEND_ENV_FILE_DEVELOP
# - FRONTEND_TEST_ORIGIN_DEVELOP

image: node:16.14-alpine

# ------------- STAGES
# List of stages for jobs, and their order of execution
stages:
  - install
  - setup
  - test
  - build
  - deploy
  - integration

# ------------- INCLUDES
include:
  - 'gitlab-ci/.shared_config.yml'
  - 'gitlab-ci/install.yml'
  - 'gitlab-ci/setup.yml'
  - 'gitlab-ci/test.yml'
  - 'gitlab-ci/build.yml'
  - 'gitlab-ci/deploy.yml'
  - 'gitlab-ci/integration.yml'
