# use docker image and service according to: https://docs.gitlab.com/ci/docker/using_docker_build/#use-docker-in-docker

variables:
  DOCKER_TLS_CERTDIR: "/certs"

build_backend:
  stage: build
  rules:
    - !reference [.shared_config, rules, on_development_build]
    - !reference [.shared_config, rules, on_production_build]
  tags:
    - docker
  image: docker:27.5.1
  services:
    - docker:27.5.1-dind
  before_script:
    - docker info
  script:
    - apk add jq git
    - |
      VERSION=$(jq -r '.version' package.json)
      SHORT_HASH=$(git rev-parse --short HEAD)
      if [ -z "$CI_COMMIT_TAG" ]; then
        VERSION="${VERSION}.${SHORT_HASH}"
        jq '.meta["version-detailed"] = "${VERSION}"' package.json > package.tmp.json && mv package.tmp.json package.json
      fi
    - docker build --build-arg VERSION=$VERSION -f backend.Dockerfile -t stromchart-backend:$VERSION .
    - echo Logging in to $DOCKER_REGISTRY_HOST
    - echo $DOCKER_REGISTRY_PASSWORD | docker login --username $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY_HOST
    - docker tag stromchart-backend:$VERSION $DOCKER_REGISTRY_HOST/stromchart-backend:$VERSION
    - docker push $DOCKER_REGISTRY_HOST/stromchart-backend:$VERSION
    - docker tag stromchart-backend:$VERSION $DOCKER_REGISTRY_HOST/stromchart-backend:latest
    - docker push $DOCKER_REGISTRY_HOST/stromchart-backend:latest

build_frontend:
  stage: build
  rules:
    - !reference [.shared_config, rules, on_development_build]
    - !reference [.shared_config, rules, on_production_build]
  tags:
    - docker
  image: docker:27.5.1
  services:
    - docker:27.5.1-dind
  before_script:
    - docker info
  script:
    - apk add jq git
    - |
      VERSION=$(jq -r '.version' package.json)
      SHORT_HASH=$(git rev-parse --short HEAD)
      if [ -z "$CI_COMMIT_TAG" ]; then
        VERSION="${VERSION}.${SHORT_HASH}"
        jq '.meta["version-detailed"] = "${VERSION}"' package.json > package.tmp.json && mv package.tmp.json package.json
      fi
    - docker build --build-arg VERSION=$VERSION -f frontend.Dockerfile -t stromchart-frontend:$VERSION .
    - echo Logging in to $DOCKER_REGISTRY_HOST
    - echo $DOCKER_REGISTRY_PASSWORD | docker login --username $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY_HOST
    - docker tag stromchart-frontend:$VERSION $DOCKER_REGISTRY_HOST/stromchart-frontend:$VERSION
    - docker push $DOCKER_REGISTRY_HOST/stromchart-frontend:$VERSION
    - docker tag stromchart-frontend:$VERSION $DOCKER_REGISTRY_HOST/stromchart-frontend:latest
    - docker push $DOCKER_REGISTRY_HOST/stromchart-frontend:latest
