build-backend:
  stage: build
  rules:
    - !reference [.shared_config, rules, web_and_push]
    - changes:
      - backend/**/*
      - package-lock.json
  cache:
    - !reference [.shared_config, cache, node_modules_root]
    - !reference [.shared_config, cache, node_modules_backend]
    - !reference [.shared_config, cache, env_backend]
  artifacts:
    name: "backend-$CI_COMMIT_REF_SLUG"
    paths:
      - backend/build
      - backend/node_modules
      - backend/.env
      - backend/ecosystem.config.js
      - node_modules
  script:
    - cd backend
    - npm run build

build-frontend:
  stage: build
  rules:
    - !reference [.shared_config, rules, web_and_push]
    - changes:
      - frontend/**/*
      - package-lock.json
  cache:
    - !reference [.shared_config, cache, node_modules_root]
    - !reference [.shared_config, cache, node_modules_frontend]
    - !reference [.shared_config, cache, env_frontend]
  artifacts:
    name: "frontend-$CI_COMMIT_REF_SLUG"
    paths: 
      - frontend/dist
  script:
    - cd frontend
    - npm run build
