live-check_production:
  stage: live-check
  variables:
    NODE_ENV: test
  rules:
    - !reference [.shared_config, rules, on_production_deploy]
  cache:
    - !reference [.shared_config, cache, node_modules]
  script:
    - echo "Running Live-Check for production server $DEPLOY_PRODUCTION_TEST_ORIGIN"
    - cd backend
    - echo "TEST_API_ORIGIN=$DEPLOY_PRODUCTION_TEST_API_ORIGIN" > .env
    - npm run test-integration
    - cd ../frontend
    - echo "TEST_API_ORIGIN=$DEPLOY_PRODUCTION_TEST_ORIGIN" > .env
    - npm run test-integration

live-check_development:
  stage: live-check
  variables:
    NODE_ENV: test
  rules:
    - !reference [.shared_config, rules, on_development_deploy]
  cache:
    - !reference [.shared_config, cache, node_modules]
  script:
    - echo "Running Live-Check for development server $DEPLOY_DEVELOPMENT_TEST_ORIGIN"
    - cd backend
    - echo "TEST_API_ORIGIN=$DEPLOY_DEVELOPMENT_TEST_API_ORIGIN" > .env
    - npm run test-integration
    - cd ../frontend
    - echo "TEST_API_ORIGIN=$DEPLOY_DEVELOPMENT_TEST_ORIGIN" > .env
    - npm run test-integration
