checks:
  stage: quality-check
  rules:
    - when: on_success
  cache:
    - !reference [.shared_config, cache, node_modules]
  script:
    - npm run audit
    - cd frontend && npm run audit && cd ..
    - cd backend && npm run audit && cd ..
    - npm run lint
    - npm run typecheck
    - cd frontend && npm run typecheck && cd ..
    - cd backend && npm run typecheck && cd ..

test:
  stage: quality-check
  rules:
    - when: on_success
  cache:
    - !reference [.shared_config, cache, node_modules]
  script:
    - npm run test-units
